### ISSUE TITLE
Applicant details for recruiter

### ISSUE THREAD

**Issue by PriyaGandhi311** [WolfByteCollective/application-tracking-system#7]
**Description:** 
Applicant details were not visible to the recruiter. Added functionality to take more details from user and show linkedinID and githubId explicitly to recruiter for better applicant filtering.

**Key Feature:**
User details are more exclusive
Applicant details to the recruiter are precise
The recruiter can directly visit LinkedIn and GitHub profiles of the user

**Acceptance criteria:**
User is able to add links to their linked in and github profiles
Recruiter is able to see all important applicant details
Recruiter can navigate to users social media profiles directly

**Comment by sdalal11** [comment]
The following functionality has been completed
